---
title: "Wisconsin Hypsography Examples"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{WI_Hypsography_Ex}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Setup

```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
library(Wisclakebathy)
library(ggplot2)
library(extrafont)

# Note: if building straight from vignette, change paths to be relative to
# vignette folder.
lake_areas <- convert_proportion_areas(path = "data-raw/Wisconsin_Hypsography",
                                       max_area_file = "WI_areas.csv",
                                       flip = TRUE)
lake_volumes     <- calculate_volumes(lake_areas, 
                                      method = "trapezoidal")
vol_loss_10pcnt  <- depth_change_given_volume_loss(lake_volumes,
                                                   pcnt_loss = 10)
depth_change_1ft <- volume_loss_given_depth_change(lake_volumes,
                                                   depth_change_ft = 1)

# To write out:
write.csv(lake_volumes, "data-raw/WI_Hypsography_incl_volumes.csv", 
          row.names = FALSE)
write.csv(vol_loss_10pcnt, "data-raw/WI_Hypsography_10pcnt_vol_loss.csv", 
          row.names = FALSE)
write.csv(depth_change_1ft, "data-raw/WI_Hypsography_1ft_depth_change.csv", 
          row.names = FALSE)

```

## Visualize

<br>

**Change in Maximum Lake Depth with 10% Volume Loss**
<br>
```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=4, fig.height=3}
plot_obj <- ggplot(data = vol_loss_10pcnt,
                   aes(x = .data$depth_change)) +
            geom_histogram(binwidth = 0.1,
                           position = "identity") +
            labs(x = "Change in Lake Depth (ft)",
                 y = "Number of Lakes") +
            scale_x_continuous(minor_breaks = 0.1,
                               expand = c(0,0)) +
            scale_y_continuous(expand = c(0,0)) +
            theme_bw() +
            theme(text = element_text(family = "Segoe UI Semilight",
                                      size = 12))

plot_obj
```

<br>

**Change in Lake Volume with 1ft Drop in Maximum Lake Depth**
<br>
```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=4, fig.height=3}
plot_obj <- ggplot(data = depth_change_1ft,
                   aes(x = .data$vol_pcnt_loss)) +
            geom_histogram(binwidth = 1,
                           position = "identity") +
            labs(x = "Change in Lake Volume (%)",
                 y = "Number of Lakes") +
            scale_x_continuous(minor_breaks = 1,
                               expand = c(0,0)) +
            scale_y_continuous(expand = c(0,0)) +
            theme_bw() +
            theme(text = element_text(family = "Segoe UI Semilight",
                                      size = 12))

plot_obj
```

